# Generated by Django 4.2.14 on 2024-07-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='last_updated',
        ),
    ]
